### ISSUE TITLE
Item images not working

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/HypixelSkyblock#14]
The item images on the startpage dont seem to work.
Example: "/static/352-0.png"

**Comment by Ekwav** [comment]
> The item images on the startpage dont seem to work.
> Example: "/static/352-0.png"

That's because the backend has no images for some items.
I will happily return icons if you give me a source.

**Comment by Ekwav** [comment]
Please use `/static/icon/{item.Tag}` to either get an icon I know about or a transparent one
