### ISSUE TITLE
Ult wise 1/2 are irrelevant

### ISSUE THREAD

**Issue by Ekwav** [Coflnet/HypixelSkyblock#54]
Ult bank min 6
Ult combo min 5
Ult Jerry min 5
Ult last stand min 3
Ult no pain no Gane min 5
Ult rend / swarm min 2 (one is half mil)
Ult wisdom min 3
Ult wise min 3

**Comment by Ekwav** [comment]
Compact min 7

**Comment by Snoe0** [comment]
Soul eater min 1-3

**Comment by Ekwav** [comment]
> Ult Soul eater min 1-3

they are all over the minimum of 1M

**Comment by Ekwav** [comment]
Fixed with https://github.com/Coflnet/HypixelSkyblock/commit/4ee1330587144d8bded70ad9c525129a552a49a6
